//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarSale
    {
        public string salesDocument { get; set; }
        public Nullable<System.DateTime> dataOfSale { get; set; }
        public string receiptDocument { get; set; }
        public string nameCar { get; set; }
        public string fiiNameEmployee { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual TheArrivalOfCars TheArrivalOfCars { get; set; }
    }
}
